// Generated by CoffeeScript 1.7.1

/*
	generator-joomla-component

	index.coffee

	@author Sean Goresht

    Modified by: Alejo Sotelo
    Web: http://alejosotelo.com.ar
    github: https://github.com/alejoasotelo

	@note uses Codoc
	@see https://github.com/mklabs/yeoman/wiki/generators coffeescript with yeoman
	@see https://github.com/coffeedoc/codo
 */
 'use strict';

 var yeoman = require('yeoman-generator');
 var path = require('path');
 var _ = require('underscore.string');

 var HelperGenerator = module.exports = yeoman.extend({

     main: function() {
         this.argument('name', { type: String, required: true });
         this.name = this.options.name;

         var pkg = require(path.join(process.cwd(), './package.json'));

         var helperName = _.slugify(this.name);
         var helperClassName = _.classify(this.name);
         console.log("You called the helper subgenerator with the argument " + this.name + ".\nNow let's create that helper as helpers/" + this.helperName + ".php for you...");

         this.fs.copyTpl(
             this.templatePath('_helper.php'),
             this.destinationPath('helpers/' + helperName + '.php'),
             {
                 _: _,
                 name: 					this.name,
                 componentName: 		pkg.componentName,
                 description:			pkg.description,
                 requireManageRights:	pkg.requireManageRights,
                 authorName:	 		pkg.author.name,
                 authorEmail:	 		pkg.author.email,
                 authorURL: 			pkg.author.url,
                 license: 				pkg.licenses[0].type,
                 currentDate:			new Date().getUTCDate(),
                 helperName: 			helperName,
                 helperClassName:		helperClassName
             }
         );
     }

 });
